<?php

namespace EAM\DefaultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findArticlesPublies($nombreParPage, $page)
    {
        if ($page < 1) {
            throw new \InvalidArgumentException('La page ne peut être inférieur à 1 (valeur : "'.$page.'").');
        }
        $query = $this->createQueryBuilder('a')
            ->where('a.publication = 1')
            ->orderBy('a.date', 'DESC')
            ->orderBy('a.id', 'DESC')
            ->getQuery()
        ;
        $query->setFirstResult(($page-1) * $nombreParPage)
              ->setMaxResults($nombreParPage);

        return $query->getResult();
    }
}
